name: Build HTML pages from Markdown

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.0 # Choose the Ruby version you need

    - name: Install Kramdown
      run: gem install kramdown

    - name: Convert Markdown to HTML
      run: |
        mkdir articles-html
        ruby convert_markdown.rb
